### ISSUE TITLE
transposition doesn't end streams, related to the HTML driver

### ISSUE THREAD

**Issue by wyqydsyq** [cyclejs/cyclejs#367]
I have an isomorphic Cycle app (diversity using latest `@cycle/xstream-run`, `@cycle/core`, `@cycle/dom`) which has a deep hierarchy of nested components (~5 deep), I've simply nested the child components' DOM sinks in the snabbdom VTree, expecting my app to be ran with transposition enabled on the DOM/HTML drivers.

My app runs fine on the client-side using `makeDOMDriver()`, but when attempting server-side rendering by swapping `makeDOMDriver()` for `makeHTMLDriver()` and `html => res('<!DOCTYPE html>' + html)` as the `effect`, the transposed streams never end, so the `effect` callback is never called and my Hapi server never returns a response.

I can fix this for the server-side by appending `.take(1)` to each nested child component (e.g. swapping `child(sources).DOM` with `child(sources).DOM.take(1)`, but this then messes with the front-end by stopping each DOM sink after its first emission.

I'm not 100% sure if the streams not ending is the cause of this issue, I'm led to believe this because adding `.take(1)` to each and every child's DOM sink (when it's referenced in the parent component nesting it in a snabbdom VTree) resolves it.

**Comment by staltz** [comment]
It's a bit hard to nail down what's going on without seeing your code, but transposition itself doesn't mean the DOM sink stream will be completed.

You need to build the app so that *any source stream which may be infinite on the client side would be finite on the server side*. For instance, if your DOM sink stream depends on `sources.DOM.select(a).events(b)`, then when the DOM source comes from the HTML driver, `events(b)` will return an empty stream, which means, a stream that only has `complete`. This is how the complete will end up propagating to the top-level DOM sink stream.

We've built transposition so that it propagates `complete`, and this is tested: https://github.com/cyclejs/cyclejs/blob/master/dom/test/node/html-render.js#L83-L104

There *could* be a bug in Cycle DOM, but as long as we can't reproduce it, we can't know for sure.

If we end up finding a bug through this discussion, the issue will be tagged bug and reopened.

For now, try following the tip I said above: *any __source__ stream which may be infinite on the client side should be finite on the server side*
