### ISSUE TITLE
Allow to isolate particular sources/sinks only

### ISSUE THREAD

**Issue by Hypnosphi** [cyclejs/cyclejs#369]
`isolate` is mostly useful for DOM isolation, and people often don't want their HTTP requests to be private to one component. Maybe `isolate` could take a list of driver names as third optional argument?

**Comment by artfuldev** [comment]
We already allow isolation by request 'category', I think, but why wouldn't a component want to isolate its http requests? If it wants to give the responses to its parent, it can send it as a stream from itself, to which the parent can most obviously react.

**Comment by Hypnosphi** [comment]
>If it wants to give the responses to its parent, it can send it as a stream from itself

But that stream shouldn't be named the same way as child's http source. Quite a non-obvious restriction.

**Comment by staltz** [comment]
I don't understand why to avoid HTTP isolation. It's only between siblings, not between parent and child. So the parent is able to get all its children requests and responses. I mean what harm can HTTP isolation make for your application?

**Comment by artfuldev** [comment]
@Hypnosphi why should it be named the say way? the request/response may not be the intent or action that the parent component wants to react to. The component can build the intent/action stream and then expose it to the parent instead of the parent having to react to the response stream of the requests made by the child.

**Comment by artfuldev** [comment]
BTW staltz is right about isolation being between siblings...

**Comment by whitecolor** [comment]
This question was already discussed https://github.com/cyclejs/cyclejs/issues/277

I would consider  "partly" isolated component to be  antipattern.

**Comment by kevinmctigue** [comment]
@Hypnosphi I was looking for this exact feature when I came across this discussion. I was assuming this wasn't the current behavior but wanted complete DOM isolation for a child, but for HTTP requests to be triggered by that child (say, a click) and the response to be processed by a parent (say, a full page response).

I was under the assumption that isolation meant all requests and responses were fully isolated to only that component, but as @staltz mentioned isolation is only from siblings. You can see how this works here https://github.com/cyclejs/cyclejs/blob/master/http/src/isolate.ts#L21...

I believe it's something like this: say you have top-level component **A** (not isolated) which has a child component **B** (isolated to `cycle1`) which is a child **C** (isolated to `cycle2`) which two children **D** (isolated to `cycle3`) and **E** (isolated to `cycle4`) so the tree looks like so:
```

A
| _ B
|   | _ C
|   |   | _ D
|   |   |
|   |   | _ E
```

Child **D**'s requests will have a `_namespace` property of `['cycle3']` which continues to get namespaces tacked on by the parent components until it's `['cycle3', 'cycle2', 'cycle1']`, then finally the request is passed to A, which does nothing additional (because it wasn't isolated) and passes it to the actual driver. When the response comes back, **A** is going to see it because it has no isolation. Then because each child component was isolated, it's going to check if the request contained its own namespace (https://github.com/cyclejs/cyclejs/blob/master/http/src/isolate.ts#L9-L10), all of which *will* except for **E**. When **E** checks for 'cycle4' and it doesn't find it, it will ignore that response.

Although I'm glad this is the functionality, it seems like a pretty fair assumption to make that components will be completely isolated. I think maybe the documentation for each cycle module should have a section called **isolate** (assuming that module supports isolation) which describes the behavior of that particular module's isolation.

**Comment by whitecolor** [comment]
@kevinmctigue this issue with the way of http (and dom) isolation was discussed pretty much. In DOM all the events are scoped exclusively to isolated component, in http-like drivers parents parents have access to child components. It was desided to leave that way, there are aslo issue about to allow DOM source ( using options) to access child isolated events from parent.

**Comment by staltz** [comment]
> I think maybe the documentation for each cycle module should have a section called isolate (assuming that module supports isolation) which describes the behavior of that particular module's isolation.

I agree.

Also, this issue is a bit stale as it seems it won't happen. I'll create another issue so we document how isolation works for each driver.
