### ISSUE TITLE
Use transposition for partly DOM update

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#386]
I heard some people show a great concern that in cycle DOM whole vtree is a subject for diffing on every state  (even tiny) update. I actually too share this concern. 

What do you think about it? Don't you see here a quite weak point of the current approach (when diff/patch is applied to whole tree on any change)? For example in React apps it is possible to only update any nested components, and redux allows to do this.

Currently transposition is just used to get the latest version for the whole tree, why not instead apply a diff patch to corresponding vnode produced by nested stream?

@TylorS what do you think?

**Comment by TylorS** [comment]
Yeah, that has been something we've thought about a lot, and I've tried to implement but failed. I'm just unsure of how to implement it. PR's and more ideas on the subject are definitely welcomed.

**Comment by whitecolor** [comment]
@TylorS 
So I haven't tried yet, maybe will look into this too. Do you think that  it worth the effort and will give performance advantage?

It would be also great to get a comment from @paldepind on this topic.

**Comment by TylorS** [comment]
Yes, I think it will have a pretty large performance benefit.

**Comment by axefrog** [comment]
@TylorS, yeah it is something I've thought about. Given that Snabbdom is only able to patch from a single node that is known about from the start (i.e. the root), it means that use of thunks can be a really important tool for avoiding unnecessary node comparison and subtree traversal. It might be worth promoting/writing about the use of thunks a little more heavily.

Another alternative might be write an extension to Snabbdom's patch code to somehow allow a prior subtree to be extracted from the patch state and use that to perform a subtree patch. The patched subtree state would then need to propagate back into the base patch state somehow to make sure that the subtree changes are not lost. I imagine the subtree would be located by way of some kind of direct selector path from the patch root to the subtree root.

I don't know what the code to do this would look like, or how patching a subtree would look in terms of the way Cycle works, but it's an idea.

**Comment by bgnorlov** [comment]
Why not allow vdom engine just subscribe to stream like yolk.js does? In this case we can not generate vdom by streams but just use vdom like tamplate `<div>{text$}</div>` instead of `text$.map(text=><div>{text}</div>`)

**Comment by TylorS** [comment]
@bgnorlov That's what transposition does, but that does not give them the ability do diffing themselves. That is what this thread is for :)

**Comment by paldepind** [comment]
> Another alternative might be write an extension to Snabbdom's patch code to somehow allow a prior subtree to be extracted from the patch state and use that to perform a subtree patch. The patched subtree state would then need to propagate back into the base patch state somehow to make sure that the subtree changes are not lost. I imagine the subtree would be located by way of some kind of direct selector path from the patch root to the subtree root.

That sounds doable I think.

I had another thought as well. When diffing Snabbdom first compares vnodes for pointer/reference equality. I.e. `vnode1 === vnode2`. If the check returns true it skips diffing and patching that entire vnode tree. It can do so because it assumes that users do not mutate vnodes. The optimization is closely related to thunks.

Maybe there is a way for Cycle to use this. A component returns a stream of vnodes, `vdom$`, if the components state doesn't change then neither does `vdom$`. Thus if the parent component uses `vdom$` in its view Snabbdom should see exactly the same vnode from `vdom$` and thus skip diffing the nested child component when diffing the parent. I'm not too sharp on Cycle, so maybe the above doesn't make sense or maybe Cycle already uses this to do optimizations.

Btw, the above can also be used to avoid diffing completely static parts of the UI. For instance in the [Cycle todo example](https://github.com/cyclejs/todomvc-cycle/blob/master/src/components/TaskList/view.js) the function `renderHeader` always returns an identical vnode tree. So instead of creating it in a function we can assign it to a constant and simply reuse it in each render. Then Snabbdom will bail on it's pointer equality check and it will never dive into the static view after the very first render.

**Comment by TylorS** [comment]
> Thus if the parent component uses vdom$ in its view Snabbdom should see exactly the same vnode from vdom$

This is often true but if your state emits, even if the values haven't changed, then your component is still generated a new call to `h()` thus still causes a check inside of snabbdom to see if anything changed. It can't do a simple equality check. That's if my understanding of snabbdom is correct, which I hope it is at this point :)

This can however be achieved using `distinctUntilChanged()/skipRepeatsWith()/dropRepeats()` depending on the stream library you are using. 

```js
// most.js
const vdom$ = state$
  .skipRepeatsWith((prev, curr) => { /* do a more useful equality check /* })
  .map(view)
```

This is however a user optimization and only works on a case by case instance. It'd be great to further optimize the internals of either @cycle/dom and/or snabbdom to improve performance out of the box. Though together they are quite fast already :)

@paldepind  Thanks for stopping by to share your thoughts. It is greatly appreciated. Also, I don't know if I've said it before, but thank you for creating snabbdom :D

**Comment by Hypnosphi** [comment]
Well, in the most common cases like

```js
xs.combine(A.DOM, B.DOM).map(vtrees => div(vtrees));
```

simple reference checking should work well

**Comment by paldepind** [comment]
> This is often true but if your state emits, even if the values haven't changed, then your component is still generated a new call to h() thus still causes a check inside of snabbdom to see if anything changed. It can't do a simple equality check. That's if my understanding of snabbdom is correct, which I hope it is at this point :)

Yes. That is correct. In that case Snabbdom will do a diff.

> Thanks for stopping by to share your thoughts. It is greatly appreciated. Also, I don't know if I've said it before, but thank you for creating snabbdom :D

No problem. You're all very welcome.

**Comment by whitecolor** [comment]
@paldepind yes thanks for your thoughts too.

Intuitively I feel that this issue should be solved without big difficulties, but I myself didn't dive deep in to it (yet).

**Comment by tusharmath** [comment]
@whitecolor 
> Don't you see here a quite weak point of the current approach (when diff/patch is applied to whole tree on any change)

I have been trying to implement something like [this](https://googlechrome.github.io/ui-element-samples/swipeable-cards) using cyclejs and also react and have failed miserably with both. I could barely get 15-20FPS primarily because of the loads of javascript getting executed on every touch move event.
From what I have learnt, any form of abstraction affects performance and there is nothing like using simple and plain javascript making changes directly to the dom. So I created a webcomponent to solve this particular usecase of mine and then used it with cyclejs and the results were — buttery smooth!

So IMHO — Snabbdom does a pretty awesome job already, though adding this functionality might make is more faster, it would not necessarily be of much use to people who want to give that native app experience on the web.

**Comment by whitecolor** [comment]
@tusharmath I see you pain) but this issue is about avoiding definitely unnecessary work by snabbdom: when you know that a particular part of data changed which referrers to particular UI part - it is more logically correct to process only this part of UI. It won't turn web app performance into native obviously.

**Comment by staltz** [comment]
It's hard to nail down what this issue is about, because it's about many things: transposition, subtree optimization, snabbdom diffing by references/pointers, userland-optimizations, so I'm labeling this as a discussion. If we agree on something specific to do, we can move it back. I certainly agree we could do a few more optimizations. The snabbdom diff by reference is a good one, I didn't know that. It (seems) is in userland though.

**Comment by whitecolor** [comment]
@staltz it is about that changes (emissions) in each inner stream (that is contained inside vtee$ - that is currently transposed) should make local vdom patches/updates of their own dom part, without need to canalize whole DOM tree.

**Comment by staltz** [comment]
How, and whether it can be done without API changes, is what we can discuss before it becomes a "to do".
