### ISSUE TITLE
Simplify drivers by making it a hodgepodge?

### ISSUE THREAD

**Issue by justinwoo** [cyclejs/cyclejs#432]
I've made an example of this before ([e.g.](https://github.com/justinwoo/ruminate-js#ruminatejs)), and I'm not too sure about this, but it would make typing Cycle.js a lotttt easier, the gist of this being

`run<A,B>(main: A -> B, drivers: B -> A)`

of course, the problem then becomes that you can't just expose a driver function for each key (you'd have to wrangle them up doing `return {a: makeDriver(sinks.a)}` and so on) and that users can just mixmatch whatever they want (`return {a: makeBlender(sinks.a, sinks.b)}`).

Could be really nice and simple or a mess. Just food for thought.

Andre's own crappy picture for this idea:

![photo_2016-09-14_20-50-54](https://cloud.githubusercontent.com/assets/2396926/18525519/186f2c54-7abd-11e6-8c9e-403ed8b1690a.jpg)

**edit**: oh yes, how could I forget? There is the big problem of figuring out what all goes where when the program starts, since we can't just extract the type data to use it. My original version includes a `init: B` such that you can pass in a proxy of members of B and then merge in the returned values of A. More discussion about this problem ITT

![16970](https://cloud.githubusercontent.com/assets/2396926/18531435/9ccdd98c-7ad6-11e6-8a06-e2a3b512c478.jpeg)

**Comment by TylorS** [comment]
Definitely think this should be done as long as we maintain backwards compatibility.

Awesome idea @justinwoo

**Comment by staltz** [comment]
`run()` would be polymorphic:

```js
run(main: Function, drivers: Object)
run(main: Function, effects: Function)
```

Examples:
```js
Cycle.run(main, (sinks) => {
  const domDriver = makeDOMDriver('#hurf');
  const httpDriver = makeHTTPDriver();
  return {
    DOM: domDriver(sinks.DOM),
    HTTP: httpDriver(sinks.HTTP),
  }
});
```

equal to
```js
Cycle.run(main, (sinks) => ({
  DOM: makeDOMDriver('#hurf')(sinks.DOM),
  HTTP: makeHTTPDriver()(sinks.HTTP),
}));
```

Tylor mentioned the opportunity for decorating the `effects` function:

> Also opens up post processing things. `Cycle.run(main, somethingIfy(driverFn))`
> On the other end of things rather than just around main
> Thought it's mostly the same

My remarks on that:

> if all sources would be streams, then we could make
`Cycle.run(main,adaptRxJS(drivers))`
> (by the way, drivers => effects)
> Cycle.run(main, adaptRxJS(effects))
> Cycle.run(main, adaptMostJS(effects))
> but unfortunately that would only work for sinks
> unless we put some deep hacks in adaptRxJS that would know how to take an xstream > DOMSource and return an "rxjs" DOMSource

**Comment by Cmdv** [comment]
does neaten things up that's for sure, what would the inner working of a driver look like to handle the partial application / currying?

**Comment by milankinen** [comment]
This is really good improvement suggestion! I already have many uses cases that could benefit from this kind if API. That said, I've played with this thought before but not yet managed to crack the the following circular dependency 😟:

If the "drivers object" is created in `effects` lazily based on the sinks, it means that we have to get those sinks from `main` (we can't use proxies yet because the keys are not known...) but `main` needs to know sources before it can be called. However, we can't get the sources because we don't have any drivers (or driver initialization functions) yet. Hence there is no way to know the keys unless either `main` or `effects` is called blindly without arguments, but that'll definitely break something...

I hope you manage to solve this and we'll see this feature in Cycle in future. 👍

**Comment by TylorS** [comment]
@Cmdv They'd work exactly the same way :)

**Comment by justinwoo** [comment]
Yeah, the concrete value problem is why in my original I have this signature

```js
constructor(init: T, main: (sources: R) => T, drivers: (inputs: T) => R)
```

which necessitates having a initial value that can be fed into the drivers (using a proxy, which then has the output of sources merged into it)

**Comment by milankinen** [comment]
@justinwoo Yes I noticed that. How about if the driver doesn't take any initial value? Are you using `O.empty()` (or equivalent) then?

**Comment by justinwoo** [comment]
Yeah, would require that or some kind of representation of `empty`.

**Comment by TylorS** [comment]
Here's a (most.js only) example that allows for this exact usage using ES2015 proxy.

http://www.webpackbin.com/4yKBM3zh-

**Comment by TylorS** [comment]
Most.js only because that's how it's written (from @motorcycle/core) and not for technical reasons

**Comment by TylorS** [comment]
There are relatively simple proxy polyfills too, though not totally complete polyfills, it does just enough for the use case at hand. https://github.com/GoogleChrome/proxy-polyfill

**Comment by milankinen** [comment]
@TylorS Yeah, Proxy could be a valid option if doing e.g. internal app where you don't need to worry about IE/(Mobile) Safari users. 👍  

About that polyfill, I think its not suitable for this case because:
> ... it invokes seal on any proxied object so that **no additional properties can be defined** ...

**Comment by TylorS** [comment]
> ... it invokes seal on any proxied object so that no additional properties can be defined ...

@milankinen  Why is that an issue? I don't think anyone should be adding properties to sources or sinks.

---

Updated this experiment to proxy over sources (including DOM Driver) automatically too (assuming ES Observable) http://www.webpackbin.com/4JY3Rg73W

**Comment by TylorS** [comment]
API is still definitely up for grabs, but I'm rather content with my webpackbin at the moment. It removes the need for StreamAdapters (I think) in favor of passing the "Observable" type you'd like your your application to use `Cycle(main, effects, { Observable: most.Stream }).run()`.

Drivers that want to provide interop can always call `Observable.from(sink$)` and work from there knowing the type of stream/observable it is working with. Drivers would no longer have to know about how to do conversions when passing things back into main() including complex Source types like the DOM driver. As I mentioned in my last comment, it's very possible to do conversions using the proxy polyfill.

If it's decided to keep conversions out of the core, with the addition of a "effects" function it becomes pretty easy to add. `Cycle.run(proxifySinks(main), proxifySources(effects))`

**Comment by milankinen** [comment]
>@milankinen Why is that an issue? I don't think anyone should be adding properties to sources or sinks.

@TylorS Updated your example to always use Proxy polyfill.
Here: http://www.webpackbin.com/4krl1Dmnb

**Comment by TylorS** [comment]
Ahhh okay, I understand now @milankinen. Thanks

I created a modified example from yours, http://www.webpackbin.com/4JCwnnQ3W
It expects an array of sinks you'll "need" `Cycle(main, effects, { sinks: [ 'DOM', 'HTTP' ] })`

It will throw if you've defined effects as a function and have not provided the sinks array. I think if we do this, we would want to do require that array only if a real Proxy is not accessible, as we wouldn't want to actually use the shim if that exists, and a *real* Proxy can handle this.

**Comment by milankinen** [comment]
Making the implementation behave differently in different runtime environments sounds dangerous. But that array of sink names might work, although it violates SSOT (both `effects` and entry point must know the used sink names). 👍 

How about if `sinks` is not an object but a function returning (and caching) sinks by name?
```js
function effects(sinks) {
  return {
    DOM: sinks("DOM"),
    MySource: MySource(sinks("DOM"), sinks("HTTP")),
    Another: Another(sinks("Another")),
    ...
  }
}
```

**Comment by justinwoo** [comment]
I think it'd be better to use TS/Flow "tuples" than to identify sink-driver
pairs by string keys. Would allow for having the structure available as an
array too.

**Comment by justinwoo** [comment]
(this is what I proposed in the typed run issue and what I'm doing with
purescript-cycle-run)

**Comment by Frikki** [comment]
Generally, referencing any object by a string is a terrible approach, because its highly prone to errors and inherently more difficult to debug.

**Comment by whitecolor** [comment]
@Frikki 
> Generally, referencing any object by a string is a terrible approach, because its highly prone to errors and inherently more difficult to debug.

Not so much if proper literal based typing involved (which soon should be the case for TS too). Without types everything is highly error prone in js)

@TylorS 
> Drivers would no longer have to know about how to do conversions when passing things back into main() including complex Source types like the DOM driver. As I mentioned in my last comment, it's very possible to do conversions using the proxy polyfill.

What about Source typings, is it possible to have proper stream typings for converted source?

**Comment by TylorS** [comment]
I don't know :)

**Comment by whitecolor** [comment]
Well, actually original issue has a little to do with https://github.com/cyclejs/cyclejs/issues/425. 

TS typings (and original issue proposal) do not refer to runtime stream conversion mechanics, for use with libs there still need make a custom typings for each driver source. Generic source definitions would be not possible at the moment until TS supports generic types passed as type params, but this is not a problem of cycle's diversity/unity, it is a current limitation of TS (though soon may be overcome).

So currently will help to get rid of adapters:
```js
import Cycle from '@cycle/base'
import most from 'most'
Cycle(main, effects, { Observable: most.Stream }).run().
```
is not a big difference from
```js
import Cycle from '@cycle/base'
import mostAdapter from '@cycle/most-adapter'

Cycle(dapater main, effects, { streamAdapter: mostAdapter }).run().
```
Though adapters maybe not such a bad stuff.

**Comment by staltz** [comment]
Because this issue is starting to look rather undoable without relying on unsupported Proxy impl in all browsers, we might end up just doing the tuple/array solution described in #404.

To guide our discussion, anyway, let's highlight the reasons why we wanted to do `sources -> sinks` fn + `sinks -> sources` fn in the first place:

(1) Theoretical elegance/symmetry
(2) Support TypeScript and PureScript type inference for main() and Cycle.run
(3) Opportunity to do effects decorators, including stream conversion
(4) ?

### (1) Theoretical elegance/symmetry

This is a "nice-to-have". Would maybe make teaching a bit easier too. But we could easily live without this.

### (2) Support TypeScript and PureScript type inference for main() and Cycle.run

We might end up making `Cycle.run` polymorphic to support either existing driver object API and driver array API, like in #404. But that still has open issues such as having driver names for (at least) good DevTools support.

### (3) Opportunity to do effects decorators, including stream conversion

Just like we can today make top-level main function decorators like `Cycle.run(onionify(main), drivers)`, the idea here was to enable effects decorators like `Cycle.run(main, adaptRxJS(effectsFn))`.

However, I *think* we can already do that with the drivers object API from today:

```js
Cycle.run(main, adaptRxJS({
  driver1: d1,
  driver2: d2,
});
```

where `adaptRxJS` would iterate over the property keys and wrap each driver function.

- - -

So it turns out that the big reason why we would pursue this issue is (2). We can "make do" with the tuple/array approach for now.

Any thoughts? Anything that changes the landscape I just described?

**Comment by TylorS** [comment]
@staltz Good summary, shares my current sentiments :+1:

**Comment by Widdershin** [comment]
Silly question time:

Why exactly do we need Proxy support to implement this style?

**Comment by TylorS** [comment]
@Widdershin Because it's impossible to know the keys ahead of time with this API. A Proxy allows you to ask for things that don't exist, and then *make* it exist and return those values.

This is what the proxy looks like

```js
const sinkProxy = new Proxy({}, {
  get (target, prop) {
    if (!target[prop]) {
      target[prop] = streamAdapter.makeSubject()
      return target[prop]
    }
    return target[prop]
  }
})
```

Currently we traverse the keys of the drivers object to create a new object that contains sink proxies to call the drivers with, but with this api we somehow have to give the effects function that object before we have know what drivers we're using.

```js
function effects (sinks) {
  // at this point sinks is the proxy and the target `{}` is empty
  
  // here we ask for something, and instead of returning undefined
  // it triggers the get() handler, creating *and* returning us a sinkProxy subject
  const DOMSink = sinks.DOM
  return {
    DOM: makeDOMDriver('#app')(DOMSink)
  }
}
```

Hope that helps :)

**Comment by whitecolor** [comment]
> Because this issue is starting to look rather undoable without relying on unsupported Proxy impl

Well eventually Proxy will land as It is a very useful thing. And if decided that is is needed the responsibility for proxy pollyfil dependency could be shift to the user, though this is a bit unsafe option of course.

So no to make cycle unsafe itself, this feature for now could be implemented as ad-hoc `run` decorator, so user that decides to use it will understand what he is doing. If this is really needed.

**Comment by staltz** [comment]
That's true @whitecolor, Proxy is supported in:

- Edge 13
- Edge 14
- Firefox 45 ~ 51
- Chrome 53 ~ 55
- Safari 10
- Node.js 6

And unsupported in:

- IE11 and below
- Safari 9 and below
- (All?) mobile browsers

So we *could* just alert to programmers to take caution when using this other type of `run()`.

**Comment by staltz** [comment]
But still, I don't want to yet make it the basis/default for Cycle.run() and Cycle Unified.

**Comment by aronallen** [comment]
I think my suggestion of making sources a Stream<sources> and sinks a Stream<sinks> would solve this and other potential future problems, isn't it worth considering?

https://github.com/cyclejs/cyclejs/issues/582

**Comment by staltz** [comment]
Referring to [this comment](https://github.com/cyclejs/cyclejs/issues/432#issuecomment-248089266), this proposal seems be now outdated since point (2) has good enough support nowadays with TypeScript. It's cool to see how Motorcycle.js took this approach, and if we see enough benefit of that approach in their community, we could eventually bring that idea here too, but for now the status of this issue has gone down from "should" priority.

**Comment by Frikki** [comment]
In addition, @staltz, motorcycle now provides a [compiler](https://github.com/motorcyclets/compiler) to compile away the dynamic parts.
