### ISSUE TITLE
Stream-library DOMSource.element d.ts is wrong

### ISSUE THREAD

**Issue by hiroqn** [cyclejs/cyclejs#451]
**Code to reproduce the issue:**
ElementFinder.call type is below
(https://github.com/cyclejs/cyclejs/blob/master/dom/src/ElementFinder.ts#L25)
`Element | Array<Element> `
but 

at every stream  d.ts file like 
(https://github.com/cyclejs/cyclejs/blob/master/dom/rxjs-typings.d.ts) is 

`Observable<Element>`

so is this type 

`Observable<Element | Array<Element>>` ?

**Expected behavior:**

```js
import {EventsFnOptions} from './lib/DOMSource';
import {Observable} from 'rxjs';
export interface DOMSource {
  select(selector: string): DOMSource;
  elements(): Observable<Element | Array<Element>>;
  events(eventType: string, options?: EventsFnOptions): Observable<Event>;
}
```

**Actual behavior:**

`elements(): Observable<Element>;`

**Versions of packages used:**
@cycle/dom 12.2.5

### proposal 

And this is Just Proposal,

#### propasal 1

ElementFinder.call type , change  `Element | Array<Element>` to `Array<Element>`

and 

DOMSource.element type, change `Observable<Array<Element>>`

#### proposal 2
this is my guess
when  selector is just empty string, DOMSource.elements return Observable<Element>(is this root element?)

so

DOMSource.elements function be overloaded to type

like

```js
DOMSource.elements(): Observable<Element>
DOMSource.elements(x: string): Observable<Array<Element>>
```

**Comment by staltz** [comment]
Hi, thank you for taking your time to send us this issue.

Both proposals are breaking changes. But proposal 2 isn't feasible because `DOMSource.elements()` could be called like `DOMSource.select('.foo').elements()` or `DOMSource.select(':root').elements()`. So let's not add selectors to the signature of `elements()`. Let's keep `elements()` just a getter.

But proposal 1 is doable, may be better to be consistent after all.

Thoughts @Frikki @TylorS ?
- - -

There is actually multiple issues reported here. xstream-typings.d.ts and rxjs-typings.d.ts need to be fixed, they are wrong at the moment. And the two proposals are unrelated.

**Comment by staltz** [comment]
Cycle DOM v13.0.0 released with this fix. The proposal part was not touched. Please open another issue for that if you still want to discuss such.
