### ISSUE TITLE
cycle/dom: cannot use the same isolate scope for parent and child components

### ISSUE THREAD

**Issue by abaco** [cyclejs/cyclejs#453]
**Code to reproduce the issue:**
```js
import Cycle from '@cycle/xstream-run';
import {div, button, makeDOMDriver} from '@cycle/dom';
import isolate from '@cycle/isolate';
import xs from 'xstream';

function Item(sources, count) {
  const childVdom$ = count > 0 ?
    isolate(Item, '0')(sources, count-1).DOM : // REMOVE SCOPE '0' AND IT WILL WORK AS INTENDED
    xs.of(undefined);

  const highlight$ = sources.DOM.select('button').events('click')
    .fold((x, _) => !x, false);

  const vdom$ = xs.combine(childVdom$, highlight$)
    .map(([childVdom, highlight]) =>
      div({style: {'margin': '10px', border: '1px solid #999'}}, [
        button({style: {'background-color': highlight ? '#f00' : '#fff'}}, 'click me'),
        childVdom
      ])
    );
  return { DOM: vdom$ };
}

function main(sources) {
  const vdom$ = Item(sources, 3).DOM;
  return { DOM: vdom$ };
}

Cycle.run(main, {
  DOM: makeDOMDriver('#main')
});
```

**Expected behavior:**

Each button is toggled red/white when clicked.

**Actual behavior:**

The inner `Item`s are not isolated from each other. Clicking any button toggles all the others.

**Versions of packages used:**

@cycle/dom: 12.2.5

@cycle/xstream-run: 3.1.0

@cycle/isolate: 1.4.0

xstream: 6.1.0

**Why anyone would want to do this:**

Because of cycle-onionify. In onionify components in a list are isolated from each other by their index (0, 1, 2, ...). Thus if you make a list of lists of lists... (i.e. a tree) of the same component, you'll end up with many parent-child-grandchild-... with the same numerical isolate scope, like in the example above.

**Comment by staltz** [comment]
Legit bug in Cycle DOM and it seems we need to concatenate all parent isolation scopes, to get e.g. `$$CYCLEDOM$$-0-0-0` for the deepest component, not `$$CYCLEDOM$$-0` for each component.

**Comment by staltz** [comment]
Note to self:

After we get Frederik's Cycle DOM refactor PR merged, we should
1. Add test that resembles the code given above
2. In MainDOMSource.isolateSink, instead of directly calling the isolateSink utility imported from the other file, we wrap that one to get the current MainDOMSource instance scope, with `const scope = getScope(namespace);` and prepend that to the scope given as argument to the `isolateSink` function.
3. Run tests. Do they pass. If not, do step 4.
4. Try to do something like step 2 also for `isolateSource`

**Comment by staltz** [comment]
Cycle DOM v14.0.0 released with this fix
