### ISSUE TITLE
Cycle run sensitive to order of sinks

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#476]
**Code to reproduce the issue:**

```js
import Cycle from '@cycle/xstream-run';
import xs from 'xstream';
import flattenConcurrently from 'xstream/extra/flattenConcurrently';
import {div, label, input, hr, ul, li, a, makeDOMDriver} from '@cycle/dom';
import {makeHTTPDriver} from '@cycle/http';

function main(sources) {
  const getTodos = xs.of({
    url: 'http://jsonplaceholder.typicode.com/todos',
    category: 'todos',
    method: 'GET'
  })

  const todoList = sources.HTTP.select('todos')
    .compose(flattenConcurrently)
    .map(res => res.body)
    .debug()

  const vdom = todoList.map(todos => {
    return div(todos.map(todo => div(todo.title)))
  })

  return {
    HTTP: getTodos,
    DOM: vdom,
  }
}

Cycle.run(main, {
  DOM: makeDOMDriver('#main-container'),
  HTTP: makeHTTPDriver()
});
```

**Expected behavior:**

xstream `debug()` should have seen a value, the vdom too and therefor the DOM sink as well, and those items should have been displayed.

**Actual behavior:**

HTTP Source does not emit.

**Versions of packages used:**

```js
"@cycle/dom": "^14.0.0",
"@cycle/http": "^11.2.0",
"@cycle/xstream-run": "^3.1.0",
"xstream": "^7.0.0"
```

- - -

Here's why:

```js
  return {
    HTTP: getTodos,
    DOM: vdom,
  }
```

does not work.

```js
  return {
    DOM: vdom,
    HTTP: getTodos,
  }
```

works.

**Rationale:** in Cycle.run replicateMany, it would subscribe to the HTTP sink first, and then to the DOM sink second, because of the ordering in the sinks object. That would mean the synchronous request would be consumed, but it wouldn't be available by the time we subscribe to the DOM sink, because response$$ is not a value-over-time (and we recently received a PR from @ntilwalli to make response$$ not be a value-over-time, because that would cause bugs).

**Comment by TylorS** [comment]
The root of the bug is a little deeper than just ordering I think. Ordering just happens to be one way to show the issue.

So here's a slightly modified test case you have here (new URL and bin.log instead of assertions)
written in most http://www.webpackbin.com/N1xnXjr-z
It has no changes, it's exactly "as-is" at the moment.

Also written in RxJS like the test case here, but `run()` has been adjusted with `.delay(1)` on all sinks in `base.ts` line 126 
http://www.webpackbin.com/Eyb1lorWz

Most.js doesn't allow for streams to begin emitting values until after next tick, in order to avoid any issues where subscription happens before or after, because the user may not really have control over things like that just like in this case. In Rx and XStream, the libraries allow for emission to occur synchronously, which is probably fine in 99% of real use cases.

I don't think solving this bug should be to add .compose(delay(1)) here in the HTTP driver, because this definitely well affect other drivers at some point in time. I actually think we should add `.delay` to the stream adapters and delay emission of all sinks to avoid this issue entirely.

Another option maybe, is to switch back to makeHoldSubject(), which also would have continued to hide this behavior, but I don't think that's what we should do either, as we switch for a reason.

**Comment by whitecolor** [comment]
@TylorS right, see my comments in the [PR](https://github.com/cyclejs/cyclejs/pull/477#issuecomment-260990418)

**Comment by staltz** [comment]
Tylor said in private:
> BTW, I haven't returned to my comment, but I think it's actually a poor solution too
It had me thinking, it could create some issues with lots of DOM APIs. Like event.preventDefault() could cease to work because it's possibly called out of the same call stack
stopPropagation() etc

- - -

> I don't think solving this bug should be to add .compose(delay(1)) here in the HTTP driver, because this definitely well affect other drivers at some point in time.

How would it affect other drivers?

> Another option maybe, is to switch back to makeHoldSubject(), which also would have continued to hide this behavior, but I don't think that's what we should do either, as we switch for a reason.

That's an option. I remember we removed it because we didn't know why we needed it, and I still think it's a good move to remove stuff we don't think we need. When we find a reason, we can be more explicit about the reason.

I think the root of the bug is related to dependencies. In the example, the internal driver consumes the HTTP sink. But also, `vdom` consumes `todoList` which consumes `sources.HTTP` which consumes the HTTP sink. So you have two dependency chains that need values:

- `sinks.HTTP` -> internals of the driver that performs the effect
- `sinks.HTTP` -> `sources.HTTP` -> `todoList` -> `vdom` -> `sinks.DOM`

So the issue is that we need to setup those dependencies first, and emit the first value later. You're right that most.js doesn't have that issue.

Question: does most.js suffer from the `event.preventDefault()` problem you described?

**Comment by TylorS** [comment]
> How would it affect other drivers?

Well, in this example, of course it only affects a driver that depends on HTTP. But technically any synchronous stream could be missed by ordering of the driver keys if the inter-dependency is similar to this example. The HTTP driver just happens to be the one we see the issue in right now.

> Question: does most.js suffer from the event.preventDefault() problem you described?

It doesn't, but there is a subtle difference from putting `.delay(1)` and how most.js' asynchronous nature works. To maybe put it in better terms, tell me if this isn't very good. A most.js Stream has a single property `source` a `Source` is analogous to `Producer` in xstream. A Source looks like this

```typescript
interface Source {
  // run *does not* emit events to `sink` in the same call stack
  // sinks can emit events synchronously all it wants after this
  run (sink: Sink, scheduler: Scheduler): Disposable
}
```

so for maybe for better example it's sort of like this

```js
xs.create({
  start(out) {
    Promise.resolve().then(() => {
      // ensure that listeners get events beginning on next tick
      // but not in the same call stack that start() is called from
      // but the producer can produce synchronously
      someProducer.addListener(out)
    })
  },
  stop() { ... }
})
```

**Comment by whitecolor** [comment]
> I remember we removed it because we didn't know why we needed it, and I still think it's a good move to remove stuff we don't think we need. 

I believe that is the meta-reason why there should be no additional timeout based `delay` for all requests in driver.

**Comment by staltz** [comment]
@TylorS would you propose something like Promise.resolve for next-tick run on the level of Cycle base?

**Comment by TylorS** [comment]
I'm not totally sure, it would break the synchronous run that we introduced with Diversity.

**Comment by whitecolor** [comment]
@staltz why do you need next-tick in Cycle base?

Option with single delay, instead of 
```ts
request$.compose(delay(0))
```
it could be something like:
```ts
request$.combine(request$, of('').delay(0))
  .map(([request]) => request)
```
but instead of this it could something else:
```ts
request$.combine(request$, xs.fromPromise(Promise.resolve()))
  .map(([request]) => request)
```
But maybe it would be better to do it without involving of promises and timeouts as I proposed a run function should be able to inform a driver that cycle "is ready, it may do using forth param of run function (along with request$, runSA, name, ready)

```ts
function httpDriver(request$: Stream<RequestInput>,
    runSA: StreamAdapter,
    name: string, 
    onReady: (fn: () => void) => void 
   ): HTTPSource {

    let ready$ = xs.create()   
    let emitReady = () => ready.shamelesslySendNext('')
    onReady ? onReady(emitReady) : emitReady()
    let response$$ = request$.combine(request$, ready$)
      .map(([request]) => request)

```

**Comment by whitecolor** [comment]
Option with single delay, instead of 
```ts
request$.compose(delay(0))
```
it could be something like that to delay responsed until ready event:
```ts

const delayUntilReady = (request$, ready$) =>
  xs.merge(
    // accumulate requests until ready
    xs.combine(request$.scan((acc,r) => acc.concat(r), []), ready$)
      .take(1)
      .map(xs.fromArray).flatten(),
	// pass through requets after ready
    xs.combine(request$, ready$).drop(1)
  ).map(([request]) => request)
  
delayUntilReady(request$, of('').delay(0))  
```
but instead of this it could be Promise:
```ts
delayUntilReady(request$, xs.fromPromise(Promise.resolve()))
```
But maybe it would be better to do it without involving of promises and timeouts as I proposed a run function should be able to inform a driver that cycle "is ready, it may do using forth param of run function (along with request$, runSA, name, ready)

```ts
function httpDriver(request$: Stream<RequestInput>,
    runSA: StreamAdapter,
    name: string, 
    onReady?: (fn: () => void) => void 
   ): HTTPSource {

    let ready$ = xs.create()   
    let emitReady = () => ready$.shamelesslySendNext('')
    onReady ? onReady(emitReady) : emitReady()
    let response$$ = delayUntilReady(request$, ready$)      

```

**Comment by TylorS** [comment]
I think I might have a solution that's quite simple.
[Here on line 124](https://github.com/cyclejs/cyclejs/blob/master/base/src/index.ts#L124) in @cycle/base 
we could do this
```js
fromPromise(Promise.resolve()).concat(sinks[name])
```

This would create a 1 time "event" stream that lasts until the next tick, and then resumes until normal.

What do you think?

**Comment by whitecolor** [comment]
@TylorS so you probably need to do this without promises in diversity `@cycle/base`

```ts
  const promise = Promise.resolve()
  const results = Object.keys(sinks)
    .filter(name => !!sinkProxies[name])
    .map(name => streamAdapter.streamSubscribe(sinks[name], {
      next(x: any) { promise.then(() => sinkProxies[name].observer.next(x);) },
```

**Comment by staltz** [comment]
> This would create a 1 time "event" stream that lasts until the next tick, and then resumes until normal.

Yeah I think that would work. It wouldn't break Cycle Diversity's sync API because in that case we can still get the sources/sinks/run from `Cycle(main, drivers)` and then call run separately. What changes is that this second part, `run()`, would happen in the next tick. I'm not sure if anyone relies on this behavior, but they shouldn't (I think).

> But maybe it would be better to do it without involving of promises and timeouts as I proposed a run function should be able to inform a driver that cycle "is ready, it may do using forth param of run function (along with request$, runSA, name, ready)

It doesn't solve the problem. If two drivers use this `ready` option, and the app logic is coded like the example above, we would still have the same bug sensitive to the ordering in the sinks object. It doesn't solve the problem.

**Comment by whitecolor** [comment]
> It wouldn't break Cycle Diversity's sync API because in that case we can still get the sources/sinks/run from Cycle(main, drivers)

It woudn't break the API, but it would change (break?) the behaviour in some cases. If you remember sync API was introduced because there was a problem with DOM driver which after run's start delayed drawing (due to `setTimeout` in the `run`) - and it has obvious visual effect. In this case again if async behaviour introduced inside of `run` this will lead to the same (a like) potential results.

Current behaviour:
- Time 0 - driver 1 (HTTP in OP) called - it subscribes to request$ 
- Time 1 - driver 1 synchronously emits response$
- Time 2 - driver 2 (DOM in OP) called - it subscribes to sink but it doesn't get response$ emitted by HTTP in Time 1 step.

> It doesn't solve the problem. If two drivers use this ready option, and the app logic is coded like the example above, we would still have the same bug sensitive to the ordering in the sinks object.

It solves it. Actually it is the same as to delay each sink (proposed by @TylorS), sinks will be delayed in a certain order too, **what it the difference where you introduce the delay in the `run` or in driver in terms of sensitive to the ordering in the sinks**? There will be no problem because. **Both** such drivers will start to listen for requests before they both actually emit something:

- Time 0 - driver 1 called - it subscribes to sink (request$) (waits `ready` event to emit response$)
- Time 1 - driver 2 called - it subscribes to sink (request$) (waits `ready` event to emit response$)
- Time 3 - all drivers are called, call subscriptions using proxySinks are made, we call `ready` handlers
- Time 4 - driver 1 receives ready event - emits response$ (driver 2 is already listening)
- Time 5 - driver 1 receives "ready" event - receives request$ stemmed from driver1 response$

It is not needed to expose `ready` event but consume it the same way as `Promise.resolve()` inside of `run` but without introducing unnecessary async behaviour.

**Comment by TylorS** [comment]
I want to mention here, that using a promise instead of a setTimeout is actually rather different. Promises are scheduled as microtasks, which actually run at the end of the current tick. Settimeout is a scheduled as a "regular" task which begins on next tick. You can read a bit about it here. 
https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by whitecolor** [comment]
> I want to mention here, that using a promise instead of a `setTimeout` is actually rather different.

Yes that is true, I stated that you possibly get not the "same" bugs, but "alike" ones. Also implementation  of native promises differs on platforms (you may see this also from the article posted). Some platforms do not still support them natively. Though promises may someday become a part of JS standard,  I wouldn't use them when they are really not needed (actually nothing should be used if it is really not needed esp, when you create a basic general purpose library) you just introduce additional dimension of potential  uncertainty in the behaviour. 

So the question is is there really need to use async Promise based microtask if it is possible to achieve it in plain synchronous way?

**Comment by whitecolor** [comment]
I have nothing against `Promises` (though @staltz seemed to always had =). Platform support and their implementation details is far then the first question. The question is are they needed here? Is this the best option to solve the issue? I think not: it just should not be here, because it may not be here.

**Comment by staltz** [comment]
This is now solved in:
- `@cycle/base` 4.2
- `@cycle/most-run` 4.3
- `@cycle/rx-run` 7.1
- `@cycle/rxjs-run` 3.1
- `@cycle/xstream-run` 4.1
