### ISSUE TITLE
BMI example alternative

### ISSUE THREAD

**Issue by wavebeem** [cyclejs/cyclejs#504]
In the [basic examples](https://cycle.js.org/basic-examples.html) from the website, one of the examples is a BMI calculator.

I think it would be great if the Cycle.js documentation used a more welcoming example (not to mention [these caveats](http://www.npr.org/templates/story/story.php?storyId=106268439) with BMI itself).

### Suggestion

Calculate the area of a rectangle in centimeters, then convert it to inches.

- **Input:** Width in centimeters
- **Input:** Height in centimeters
- **Output:** Area in centimeters
- **Output:** Area in inches

This would have the same number of inputs and outputs as the current example, so I think it would be a good choice. But many other choices would be good too, such as reformatting a multi-part name in various ways.

**Comment by tusharmath** [comment]
It would be really great if the example could contain some list considering #312 is still open.

**Comment by staltz** [comment]
I can see concern about BMI, however in no case has it been used in Cycle.js to categorize into underweight/normal/obese. We just calculate a number. It may very well be a silly number, but it's just an impartial number which is actually used by many institutions for different purposes. The most important reason why we should keep this example is because we already have repeated it in multiple talks and videos, so eliminating it from the codebase would create broken links and also broken learning resources. Sorry. We'll keep on making sure the example is not used for categorizing people.

**Comment by wavebeem** [comment]
Hi @staltz, thanks for taking the time to reply to this.

I want to be clear that I'm not campaigning to remove the example from the code base entirely, as I totally understand that further education has been built on top of it. I'm just suggesting to have a different example on the Cycle.js home page.

I appreciate that it does not pass judgment by assigning a category, but even just bringing up a weight input can be kind of anxiety inducing.

I will respect your decision to keep this closed if you choose, but I wanted to clarify my stance.

**Comment by Widdershin** [comment]
I wonder what a good replacement example could be (for the front page)?

**Comment by Widdershin** [comment]
I had an idea, perhaps we could have an interactive mortgage repayment calculator. That's something our users are more likely to be asked to build.

**Comment by staltz** [comment]
@Widdershin I think our biggest problem is still this:

> we already have repeated it in multiple talks and videos, so eliminating it from the codebase would create broken links and also broken learning resources.

But another example would be useful, of course.
