### ISSUE TITLE
Cycle Unified adapt singleton?

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#539]
I've looked how cycle unified implements compatibility with other libraries using singleton `adapt`, `setAdapt` and I think it is a really arguable idea. I understand that the idea behind this is to simplify things for driver developers, in this case, it is done by imposing bad design and architecture in general.

I think `adapt` should go as before the second argument to a driver as `runSA` before, without introducing this weird global dependency:

```ts
import {adapt} from '@cycle/run/lib/adapt';
```
What was the reasoning behind the decision over using `adapt` as an argument to a driver? Yes it may make driver a code a bit trickier but at least it would be correct won't introduce any potential conflicts.

**Comment by staltz** [comment]
You should have risen this concern when we were discussing #425 (it lasted months) or while Unified was in release candidate.

The reason we did it like that is we want to optimize Cycle.js for people building apps with Cycle, not for people maintaining Cycle. In a different example, one could argue that OOP is bad design and architecture, but we use OOP all over the place internally in Cycle.js, because we're not optimizing the framework code in the same way we are optimizing userland code.

**Comment by whitecolor** [comment]
> You should have risen this concern when we were discussing #425 (it lasted months) or while Unified was in release candidate.

The last couple of months I had no time to track how unified is implemented. I'm not here to just criticize current solution but try to justify it or to think about better approach.

> In a different example, one could argue that OOP is bad design and architecture, but we use OOP all over the place internally in Cycle.js, because we're not optimizing the framework code in the same way we are optimizing userland code.

This was discussed before, this is the matter of internal library design, it is going to cause any potential conflicts, and OOP for this stuff is a better choice anyway. Singleton pattern itself is not safe from being a source of external conflicts and always looks like a clumsy hack so it should be avoided if possible (sometimes it is really not possible, that it is ok to use it).

> The reason we did it like that is we want to optimize Cycle.js for people building apps with Cycle, not for people maintaining Cycle.

People who developing drivers or other components for others as well should be fully aware of the architecture and understand what they are doing. And such code should be safe. Introducing this singleton imposes some assumptions, that should be considered too.

For example, from docs:

> Note that adapt is always imported from as @cycle/run/lib/adapt, not from @cycle/rxjs-run/lib/adapt nor @cycle/most-run/lib/adapt. Before returning a single-stream source from the driver, make sure to call adapt:

So simplification is arguable, but using bad pattern is quite obvious.


Another thing too:
> It is usually better to write drivers in xstream, since you don’t need to convert the sink, and given xstream’s tiny size as a dependency.

Even if sink comming to driver was not always `xstream` it would not be a big deal of converting it with `xs.fromObservable` (for xstream based drivers), so this thing is too arguable simplification. And the whole core could not depend on `xstream`, in my view it would be just more clean and abstract design of cycle's run core. And still would allow to position xstream as first class citizen while doing the same thing for other stream libs. 

I'm not saying that it is all critical just a food for thoughts about better design.

**Comment by staltz** [comment]
(Labeled discussion because there are no suggestions in this thread yet)

something-to-xstream conversion is easy to handle, you just need to do `xs.from(something)`.

xstream-to-something conversion is the job of `adapt`, and it's needed:

- In (xstream-based) drivers when returning a source stream
- In `@cycle/run` to convert sink proxies when passing them to non-xstream-based drivers

`setAdapt` is the only mutation of the singleton, and it's called **once**, when `@cycle/something-run` is imported.

The only case so far where mutation of the singleton expresses itself is when you have a **test case for a driver which tests the same driver using multiple different `@cycle/something-run`, which is rare**. That is the only real problem that happens due to the singleton. Ugliness is not a problem, it's an aesthetic preference. We wanted `adapt` to be available in the global context without worrying about passing arguments around. And that's not a problem at all, what makes it a singleton is not `adapt` (it's just a function, like `makeDOMDriver` is), what makes it a singleton is `setAdapt`.

This singleton-based solution as opposed to passing adapters as arguments is an improvement for code maintenance both in Cycle.js code and driver code. Remember that with adapters we had to do `myDriver.streamAdapter = XStreamAdapter;` which is also arguably weird.

The important thing is that the new version removes adapters and `base`, making it easier for driver authors and Cycle.js maintainers, and that was only possible because:

- xstream is the engine everywhere
- ES Observable interop for conversion something-to-xstream
- `adapt` for conversion xstream-to-something

If this discussion is all about "setAdapt is mutable and this mutability can theoretically bring some problem in some corner case", it's not worth doing a re-architecture at this stage where Unified is already out, and the real consequences of the mutability are already known and rare. We have many more important issues to work on.

**Comment by whitecolor** [comment]
Ok, I understand your point. The thing is that there is a strict limitation: one stream library for `run` function per runtime environment. Other cases are not officially supported. (this may be mentioned in docs explicitly).
