### ISSUE TITLE
Conditional preventDefault [title edited] 

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs/cyclejs#611]
With the current `@cycle/dom` version, you can specify an option to let the driver call `preventDefault()` for you (keeping side effects outside of your app).
In #65 was the idea of a predicate function that could be used to conditionally `preventDefault`. The question is now, is that needed? Does anyone have a valid use case for that type of behavior? For more information about how this would look like, see https://github.com/cyclejs/cyclejs/pull/606#issuecomment-301862166

**Comment by fuunnx** [comment]
I think the case of the conditional `keyDown` event is the most common:
I would want to call `preventDefault()` when the user presses the `enter` key in a form input, but not when he is typing.

**Comment by staltz** [comment]
Very good point, and indeed, we even have an example where we preventDefault on `tab` pressed: 

- https://github.com/cyclejs/cyclejs/blob/91d56057bf5b1cafe6d56d554ff0da3c92092f65/examples/autocomplete-search/src/app.js#L132-L133
- https://github.com/cyclejs/cyclejs/blob/91d56057bf5b1cafe6d56d554ff0da3c92092f65/examples/autocomplete-search/src/app.js#L281

So I would say, yes, we certainly need conditional preventDefault.

**Comment by staltz** [comment]
We just need to discuss what kind of API to use to provide this feature. I feel like a predicate function would follow the *principle of least surprise*. But a function might break use cases that @aronallen raised, like when crossing execution boundaries (WebWorker). The other option discussed in #606 was inspired by Ramda's path, as @jvanbruegge mentioned. Maybe there is yet another possible API?

**Comment by jvanbruegge** [comment]
As supporting a predicate function is rather easy with `typeof X === 'function'` vs `typeof X === `object`, we could support both too, so the possible input would be:
```ts
type PreventDefaultOpt = boolean | (a : any) => boolean | ComparatorObj:
```

**Comment by staltz** [comment]
Good idea! It doesn't need to be either-or. :) 👍

**Comment by aronallen** [comment]
@jvanbruegge maybe we should keep the comparator object simple for now.
simply a key value comparison where every predicate must strictly equal
e.g.

```
preventDefault: {keyCode: 13}
```

**Comment by staltz** [comment]
The only thing I'd worry about a polymorphic signature is the code size needed to implement it. I think 1kB or 2kB is the maximum before having to consider putting it in an external plugin or something.

**Comment by jvanbruegge** [comment]
the heaviest part will be the comparator object API. The other two will oneliners. We can implement @aronallen's version and further expand on that on need

**Comment by aronallen** [comment]
So just as I thought we only needed to prevent default in simple cases, I ran into an issue. I am trying to make an input field that only allows numbers.

**Comment by fuunnx** [comment]
@aronallen maybe in your case it is more a UX problem?

IMO we should not prevent any keystroke on an input because it's an unexpected behaviour. If you do this "by hand" you would have to not prevent default on other special keys that are not numbers: `backspace`, `arrow keys`, `tab`, shortcuts, copy/paste… It's a lot to take into account for the developper and you may miss something and in most on the case it's not worth doing.

However letting the browser handle it its own way with <input type="number"> has its own advantages because the user would not see its habits changed. The behaviours are different on a browser basis:
- Chrome prevents anything that is not a number
- Firefox allow everything, and displays a warning on blur

As a user I would prefer to see my text stripped on blur, after a small timeout, or just see a warning.
But of course you may have your good reasons and it's still a good point =)

**Comment by staltz** [comment]
> So just as I thought we only needed to prevent default in simple cases, I ran into an issue. I am trying to make an input field that only allows numbers. I want to prevent default if the charcode isn't a number

These more advanced use cases are convincing me that @abaco had a good insight in pointing out that this preventDefault option in the DOMSource is a write effect, and would fit better in a sink stream. E.g. using operators is so nice in this case `input$.filter(not(isNumber))` and pass that to the preventDefault. The problem with that approach is just that it's sensitive to ("Rx") scheduling, but in practice it should work because xstream and rxjs5 are synchronous-recursive by default.

So: I'm not sure we should do this proposed feature. We need more discussion, I'd say. Even though I said

> So I would say, yes, we certainly need conditional preventDefault.

:)

**Comment by Jamesernator** [comment]
PreventDefault is definitely a write effect, so it should be an output. My main concern is relying on xstream/rxjs being synchronous recursive is not a great idea as then people might accidentally hit bugs where they `.merge` or something with a stream they didn't even know wasn't synchronous.

It'd be nice if there were a variant of xstream that prevented operators being used if it would cause the response to become (potentially) asynchronous (or at least if that was tracked so that the output for preventDefaults could detect if the stream has suddenly become asynchronous).

**Comment by staltz** [comment]
Note: https://github.com/cyclejs/cyclejs/issues/651 provided a new use case where we may need conditional preventDefault: when pressing cmd or shift or ctrl.

**Comment by aronallen** [comment]
So I have been using a simplified API for achieving conditional prevent default. I am using my simple object method as described above. I have been around some different use cases, but it seems a viable approach. In the odd case you need to match something like Ctrl+UP or Ctrl+DOWN you can just create two listeners from the DOM source.
```javascript 
DOM.select('div').events('keydown', { preventDefault : { ctrlKey: true, keyCode: 38 } })
DOM.select('div').events('keydown', { preventDefault : { ctrlKey: true, keyCode: 40 } })
```

I would suggest we make the following the official API
preventDefault can be a 'true' to always prevent.
preventDefault can be a nested map with values that all must match to invoke preventDefault
preventDefault can be a method that returns a boolean indicating whether to invoke preventDefault.

```typescript
{ ... , preventDefault?: true | object* | (e: Event) => boolean }
```
 \* a serializable JSObject

**Comment by jvanbruegge** [comment]
I also think this would be the best API
- it is foolproof, you do not have to rely on synchronous stream execution
- it is not really a write effect, because instead of imperiativly stating "preventDefault if ...", you state "if it's a X event, give me a defaultPrevented event, i dont care how you do it"
- it's already implemented in https://github.com/cyclejs/cyclejs/pull/615/files

**Comment by fuunnx** [comment]
I like your API Aron, it feels natural (and looks close to the [TC39 pattern matching proposal](https://github.com/tc39/proposal-pattern-matching) ^^)

My question is, will it return all events or only defaultPrevented (matching) events ?
If it's the latter, I think it should be explicit that it's filtered, maybe something like:
```js
DOM.select('div').events('keydown', { matches : { ctrlKey: true, keyCode: 40 }, preventDefault: true })
```

**Comment by staltz** [comment]
I'm inclined to accept Aron's proposal:

```typescript
preventDefault?: true | object* | (e: Event) => boolean }
```

The discussion around read/write effect is complicated, because observing the event is read effect, but the way the DOM works is that the original event will cause a side effect. So let's say, if you don't preventDefault, it means that the original event is happening in the external world and this event may mutate the external world, *regardless* if you observe it or not. To prevent default is basically to affect how that event would originally behave. It's sort of twisted, and due to how the DOM was originally designed. It's a bit hard to hide away these DOM design choices, and might be better to configure it in the DOMSource, than to make a preventDefault sink driver.

**Comment by jvanbruegge** [comment]
I've updated #615, resolved the merge conflict and added support for a nested matcher.

**Comment by aronallen** [comment]
@fuunnx the API won't filter events, it will simply invoke prevent default on matching events, you may still be interested in the event even if preventDefault wasn't invoked.
