### ISSUE TITLE
Discussion on official approach to Styles and CSS-classes

### ISSUE THREAD

**Issue by aronallen** [cyclejs/cyclejs#613]
Hi,

I would like if we opened up a discussion on styles and classes in Cycle, should we find a way to define css classes that follows cycle principles of no side-effects?

There are a plethora of css-in-js solutions out there, personally I found [styletron](/rtsao/styletron) by @rtsao (who was at the first cycleconf) to be the best.
I especially like the atomic structure.

Styletron could easily be implemented as a snabbdom module.

The best thing about styletron is that it doesn't allow for parent > child combinators.
The worst thing about styletron is that it doesn't allow for parent > child combinators.

I would imagine we could add a `css` attribute to vnode options when creating vnodes.
```h('h1', {css : {color : 'red'}}, 'hello')```

I think we could benefit by having an official way to deal with classes and styles. I think not having parent > child combinators is a bit inconvenient, but it saves you from so many potential pitfalls down the line.

Styletron still has some open-issues, like vendor specific pseudo selectors, but I am sure ryan is open for any help here.

It would also be great if the css object could be typed, with autocompletion for all style attributes.

**Comment by staltz** [comment]
Hey @aronallen, I agree with you there should some official recommendation for CSS styles in Cycle.js, just because it makes it easier for beginners to know what is the best practices and just be able to deliver code without analysis paralysis.

That said I would prefer to **make the best practice become official**, instead of **making the official become best practice**. This means we should, as a community, reach a consensus on what is the most fitting CSS-in-JS solution.

Personally, I prefer TypeStyle, and I don't bother so much with its side effects to inject styles in the page. But you had very good points.

I think it would be awesome to have a snabbdom module for CSS, and I think we can build this as a separate package and ship it independently from Cycle.js, so other people can use it even if they don't use cycle or cycle dom.

About the parent>child selection, some CSS-in-JS libraries allow you to do that. I feel like we need to consult one of those feature tables that compare all of the CSS-in-JS options out there, and then pick that which fits Cycle.js criteria better. After that, experimentation in the wild until we get a consensus or at least 70% majority agreement.

**Comment by aronallen** [comment]
@staltz well everything should not be about my web workers, but the reason I think a snabbdom module would work better, is simply because you may not have access to the DOM where you define your styles (and thus style injection)

I think this could easily be implemented as a snabbdom module, and not something cycle specific. 

I am aware parent>child selection is possible in some libs, but it is a powerful and dangerous concept.

I would also like we revisit the idea of closing discussion issues, they get kind of forgotten (try to take a look at the other discussion issues, not much discussion after they are closed).

**Comment by TylorS** [comment]
:+1: For TypeStyle. I use TypeStyle on my current project at work, and have been very happy with it.

It'd be fairly simple to create a snabbdom module for TypeStyle, if decided upon.

**Comment by staltz** [comment]
I've learned that style management works when the *element selects the style*, not when the *style selects the element* (typical CSS selectors). Just as a reference, https://styled-components.com/ does "element selects the style", but mostly through an inheritance scheme. As a lesson from OOP, composition is better than inheritance.

So I believe (let me know if you agree or not) that CSS-in-JS should:
- Allow the element to pick the style
- Allow the style to be built/composed from smaller pieces of style

Those can be accomplished with TypeStyle, but actually the API is not the best for composition. The signature `styles(s: object): string` means that you get a classname as result, but you can't compose multiple classnames to become one classname. So exporting the hashed classnames isn't the ideal. Maybe the best would be to work only with style objects, and then the snabbdom module would internally create the classname.

What do you think?

- - -

> I would also like we revisit the idea of closing discussion issues, they get kind of forgotten (try to take a look at the other discussion issues, not much discussion after they are closed).

We used to have a link to the discussion issues on the README.md, we should restore that somehow. But for fairness with everyone who initiated discussion issues, I'd like to keep it consistent and follow the rule always, unless we change the rule.

**Comment by TylorS** [comment]
> work only with style objects, and then the snabbdom module would internally create the classname.

That's what I was thinking as well

**Comment by staltz** [comment]
Onto the details, it's not so simple to implement, specially when considering server side rendering.

- In cycle/html, how would the API be for collecting the stylesheet string?
- When server side rendering, how do we build the full html string that contains body and also stylesheet? (Suppose we are writing examples/isomorphic)
- On the client side that continues from server side rendered HTML, how does the dom driver call TypeStyle setStylesTarget() ? Does it create the styles target? Does it use something existing?

**Comment by TylorS** [comment]
I think on the server we might have to pass in a slightly different snabbdom module. I'll think on that a bit more

**Comment by aronallen** [comment]
This is my styletron implementation, it is just a snabbdom module that does away with class names entirely.

```typescript
const styletronInstance = new Styletron();

const updateStyle = (oldNode, newNode) => {
  const cssRef = newNode.data.css || []
  const cssList = Array.isArray(cssList) ? cssRef: [cssRef];
  let classNames = '';
  for (let i = 0; i < classList.length; i++) {
    classNames += `${styletronUtils.injectStyle(styletronInstance, classList[i])} `;
  }
  newNode.elm.setAttribute('class', `${newNode.attr.className} ${classNames}` );
}

export const styleModule = {
  create: updateStyle,
  update: updateStyle
}
```

**Comment by Frikki** [comment]
This is interesting, especially seen in the light of the HTTP/2 protocol, which encourages pushing CSS separately.

**Comment by sklingler93** [comment]
I know this is an old (closed) issue, but I've been working on a snabbdom module that I think addresses the issues outlined here.

Inspired by @aronallen's Styletron implementation, [snabbdom-typestyle](https://github.com/sklingler93/snabbdom-typestyle):
* Allows you to work with only style objects, internally creating the classname
* Allows you to collect styles server-side with `collectStyles(node: VNode): String` and the `serverSideCssModule`
* Removes the duplicate style element when the app is hydrated client-side

Let me know if you find it useful!

**Comment by cyrus-za** [comment]
I will start my comment off the same way as @sliptype did 😉 
> I know this is an old (closed) issue, but...

I know this is an old (closed) issue, but I only recently stumbled upon cycleJS and after watching some talks by @staltz and reading up on some code and snappdom docs etc. Coming from React, the first thing I did was to check if cycleJS is compatible with my beloved [styled-components](https://github.com/styled-components/styled-components) and unfortunately I could not find a implementation after about 5min's of googling around. (please let me know if there is one). 

What I did however find was [this article](https://www.johanbrook.com/writings/styled-components-vdom/) by @johanbrook which seems even better. I usually do not like when people use classnames as a single style e.g. `mt-5` coinciding with `margin-top: 5px` as it is pretty much the same as just inlining the styles and using the `className` attribute of an element instead of the `style` element kind of defeats the purpose of classes in the first place. I would much rather create a component which has a string of css applied with template literals (i.e. styled-components) and then using that variable in my JSX as if it is an html element or just any other "react" component that passes props down. However, the way that article presents using the single classes as a way of expressing CSS in a functional way and re-using that as the selector when creating a VNode is brilliant. This way we can still have our components be named variables (or constants) with the css applied to it and it will just work out of the box with the VDom.

**Comment by fuunnx** [comment]
@cyrus-za Nice blog post, thanks for sharing. The concept is seducting

I'm not using this approach in production yet, still sticking to good old css, but I've followed a similar path in my experiments but with inline styles (and not only styles) :

https://gist.github.com/fuunnx/e81c86cc46a485786f8193563d550680

**Comment by staltz** [comment]
@cyrus-za On styled-components, are you aware of `@cycle/react`? This means you can use React (as a rendering layer) with Cycle (as a framework), and thus you could use styled-components.

**Comment by cyrus-za** [comment]
> @cyrus-za Nice blog post, thanks for sharing. The concept is seducting
> 
> I'm not using this approach in production yet, still sticking to good old css, but I've followed a similar path in my experiments but with inline styles (and not only styles) :
> 
> https://gist.github.com/fuunnx/e81c86cc46a485786f8193563d550680

Nice but type-style feels rather clunky to me. I want native css with proper intellisense. I also want to be able to copy paste css from other online templates without refactoring. So template literals is the way to go for me. 

> @cyrus-za On styled-components, are you aware of `@cycle/react`? This means you can use React (as a rendering layer) with Cycle (as a framework), and thus you could use styled-components.

I did not know about that. That is pretty cool, but does that not kind of defeat the purpose of the small rendering lib?

**Comment by staltz** [comment]
> but does that not kind of defeat the purpose of the small rendering lib?

Isn't it good to have a choice? If you want a small and fast rendering library, choose Snabbdom, if you want a rendering library that is compatible with many community components and libraries, choose React.

**Comment by cyrus-za** [comment]
What if you want a small rendering lib that is compatible with other
libraries but as an opt-in basis? Not one that has thousands of lines of
code to support things that you wont even use? :)



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/28/19,
5:24:59 PM

**Comment by BernardJiang** [comment]
> On styled-components, are you aware of `@cycle/react`? This means you can use React (as a rendering layer) with Cycle (as a framework), and thus you could use styled-components.

@staltz , do you have an example of cyclejs framework + styled-components as renderer? I tried. Haven't figured out how to use styled-component in view function. No className, TypeError: Cannot read property 'transformOrigin' of undefined, ...
