### ISSUE TITLE
Automatic observation in VDOM

### ISSUE THREAD

**Issue by kylecordes** [cyclejs/cyclejs#614]
I've found my Cycle code has quite a bit of boilerplate in view code, around combining and mapping multiple observables. Simplistically, it ends up with a chunk of code at the start of each view function - a source of merge conflicts. Or less simplistically but more performantly, one can further entangle mapping with VDOM to recreate less VDOM unnecessarily. These things are much discussed in #204.

Reading about CALMM's Karet:

https://github.com/calmm-js/karet

...  I wonder if something similar is workable with Cycle? Some better VDOM driver that understands embedded observables, and "does the right thing". Offhand it seems that notion could fit reasonably in Cycle's architecture. If such a thing exists, I'd appreciate a pointer. Or tips on how to achieve it.

(I put this in as an issue rather than on Gitter, so that the next person searching can find it down the road.)

**Comment by staltz** [comment]
Hi Kyle. We had this type of feature long ago in Cycle.js, we used to call it "transposition" and recently we've decided to drop it in Cycle Unified: https://cycle.js.org/releases.html#cycle-unified-breaking-changes

We used to be quite excited about it, but it turns out it looks and behaves a bit too magically for the average beginner, and turned out to be a source of confusion even though it was neat. Overall the need for a combine prior to vdom creation is not that big of a hassle. Additionally, removing transposition simplified the implementation too, specially when supporting multiple stream libraries.

@TylorS can comment more if he feels like adding something.

**Comment by kylecordes** [comment]
@staltz Ah, thanks, that reasoning sounds right on, particularly about ease of understanding for beginners. Is such a thing possibly as an option add-on, though? Either as an extension/replacement cycle/http, or a function to pass vdom through on the way to cycle/http?

I've found that I can't resist the simplicity of just xs.combine()ing at the top - when more complexity could avoid needlessly recreating an entire component's VDOM, when only a small portion could have changed.

**Comment by typeetfunc** [comment]
@kylecordes https://github.com/motorcyclejs/motorcyclejs/issues/35

**Comment by staltz** [comment]
> when more complexity could avoid needlessly recreating an entire component's VDOM, when only a small portion could have changed.

In the rare occasions that I use React, I'm very aware of this issue, because creating a deep tree of ReactElements (equivalent to VNodes) is expensive and that shows clearly in performance. However, I've surprised myself with snabbdom, that creating thousands of VNodes didn't affect framerate. It does affect GC, though, but not that visibly to the user. In those cases, you can use a snabbdom `thunk` to avoid recreating a portion of the tree.

**Comment by kylecordes** [comment]
@staltz Ah, interesting. I was aware that React's VDOM implementation is a bit heavy, but not aware the difference was so stark. I will assume the straightforward single xs.combine() at the top of each view is performant enough until measurement shows otherwise.

@typeetfunc Thanks... that will take some reading and thinking.

(I admit I am a bit fuzzy on how Cycle and Motorcycle fit together - I know the answer used to be "like Cycle, but with Most and Snabbdom", but now Cycle can use Most and does use Snabb. Wish there was a wiki page or whatever with an up-to-date explanation.)

**Comment by geovanisouza92** [comment]
@staltz What do you think about some kind of Ahead-of-Time Compilation to convert vtree's written with transposition, to a non-transposed syntax (Am I make sense)?

**Comment by kylecordes** [comment]
@geovanisouza92 Speaking of AOT, I am very (very) familiar with Angular, which has a slick AOT implementation for its template syntax. It has lots of advantages, and as tooling support improves, few disadvantages. Vue.js is somewhat similar in this way, offering build-time compilation of templates.

But.

There is one key limitation of systems which AOT: they are inherently less dynamic than systems which don't AOT. With an AOT system, you can't use the same tools programming at runtime, to make new "components", as are used during development. This makes some ideas, like generic, runtime generation of complex UIs, less achievable.

Currently, Cycle is 100% dynamic. I'm hesitant to recommend moving away from that. I'm thinking the automatic-observation idea (modulo @staltz 's point about ease of understanding for beginners) would still allow complete dynamism.

**Comment by staltz** [comment]
I think the biggest problem with transposition for Cycle.js is that it makes it hard to visualize in dataflow, and we're likely going to focus more and more on Cycle.js as a framework where you code through visualizable dataflow graphs. A `combine` of multiple vdom streams is flat in the dataflow chart and is easily visualizable either in paper sketches or DevTool and beyond. How do you sketch transposition as a dataflow graph? It's hard because transposition is both "combineLatest" and "flatMap" intertwined in the vdom tree. Flatmap itself is already hard to visualize in a dataflow graph. 

Don't get me wrong, I *understand* the nice side of transposition, I came up with it independently, I thought it was my own idea, but it's so simple it could be co-invented elsewhere. Transposition is also similar to the react mental model where you embed an *dynamic instance* of a component inside another component.

The verdict is that this is a feature that, despite being cool, doesn't fit well with the guiding principles in Cycle.js: explicitness (or "traceability"), visualizable code, readability over writability.

**Comment by Frikki** [comment]
**This comment isn’t particularly relevant to the thread.**

@kylecordes, with Motorcycle, we use [mostly-dom](https://www.npmjs.com/package/mostly-dom), a derivative of snabbdom with some rather large breaking changes and design differences. "Drivers" are no longer special in Motorcycle, instead it’s possible to design the effectful side of your application using just functions as one would in the _main_ function. Motorcycle, because of the different run type signature, requires a browser that supports ES2015’s `Proxy`. 

If you’d like to know more, head over to the [Motorcycle chat room](https://gitter.im/motorcyclejs/motorcyclejs)

**Comment by kylecordes** [comment]
Indeed, we are stretching the connection to original topic. But... speaking of VDOM, perhaps the thing I like least about Cycle, is that cycle-dom appears to be mostly untyped and offers no compile-time or in-IDE assistance about the structure of h() properties. `mostly-dom` looks pretty compelling, therefore. Still, I suspect I'm better off not dividing attention between cycle and motorcycle (yet?).

**Comment by staltz** [comment]
That's just a matter of doing it, I believe most of those typings could be done in Cycle DOM. PRs welcomed. :) Sometimes with the cross-pollination between Cycle and Motorcycle it's hard to keep up-to-date on either of the sides.

**Comment by 3n-mb** [comment]
I want to second @kylecordes in
> I've found my Cycle code has quite a bit of boilerplate in view code, ...

My uneasiness feeling comes from using `.select()`. I haven't selected anything from dom in years. Hence, it feels like an unnecessary chore.

#### Cycle as general tool, vs more narrow task of html-based UI (setting conceptual context)
It is true, that cycle grew as a UI building tool. UI provides a good ground for testing the tool, and showing its awesomeness. But, with visualization of data flow, cycle becomes a much more general tool.
Therefore, we may look at creating html-based UI as one more task. And this task may have different solutions that are built and work on cycle's.

#### HTML flow, as it is done with existing approach: driver, isolate, ...
It seems to be a common pattern:
1. Select elements from dom, to assemble actual sources, which event should push our component.
2. Wire business logic circuit starting with sources, all way to things that either displayed in dom, or regulate structure of dom.
3. Consume things, generated by logic, turn it into html-respresenting structure, sinking it downstream.

Of cause, separation between items 2 and 3 depends on task, at hand. When it is something like beautiful matrix multiplication example by @staltz , there is no clear boundary. But when it is a case of boring form, or form-like UI, or UI that doesn't transform much, has tons of truly html things, separation between 2 and 3 is usually very clear indeed.

The boring case is the majority of what is written. Even the name, *business* logic, gives it away.
The reason I haven't been doing any dom *selection* for years now, is that boilerplate of 1 and 3 is done by template system.
I also had, once, 2.5 year ago a place with really nice dynamic UI component, which was on a brink of insanity, when written in angular's template. Cycle's raw creation of elements would've simplified that problem for me.

#### Template vs raw dom dump is a false dilemma for current cycle
It may seem that react-like style of assembling dom at the bottom of data flow and use of templates like vue or angularjs are incompatible, forcing devs to choose either-or (mind you, this polarization is a great marketing tool :smiling_imp: )
I'd argue that vue/angular-like template system for components can be done on top of cycle, with use of dom driver directly still available as a row, more flexible tool, for places that cannot be served by much simpler templating.

The unexpected awesomeness here will be that, when template system is written cycle, at runtime it creates *boilerplate* circuitry around business logic circuitry, and mechanics of template becomes observable in cycle devtool, giving total introspection into an opinionated template tool. Template tools have to be opinionated, because they have to *implement* items 1 and 3. The problem with opinions is that they can be surprising to user, when user tries to catch a bug. Observability in cycle devtool will totally eliminate such surprise.

#### Templated components lib
Of cause, templates should be a library. This has no place in cycle's core.

Of cause, at least initially, template should be simple: places for named sources, places that use memory streams (or signals, or pullables, can be updated, when cycle gets these). Couple of directives like vue's `v-if` and `v-for` is enough for simple components, which is the best place to use template approach. Filters have no place in templates. Filters are things inside event/data pipeline/stream.

Template system takes care of item 1 and 3, thus, wrapping business cycle item 2. So, given main function `businessLogic(sources) => sinks`, creation of template-d component may look like
```typescript
TemplatedComponent(template: string, businessLogic, sources) => sinks
```

Of cause, templated system should have a registry of known components, so that html tag `<my-component>` is mapped to registered component creating function.

Of cause, since templated system is tasked with insertion/removal of html, it should have its own opinionated routing.

A particular template system library may have its own specific hooks for devtools. Click on source of clicks, and devtool shows html element that produces clicks, and a place in a template. There is a room to go wild.

No matter how template system is done, it becomes transparent in devtool. No other framework has this magic!
With such lib, cycle has a great chance to go mainstream, I feel.

**Comment by 3n-mb** [comment]
Let's put counter example into template-d form.
Original is
```typescript
function main(sources) {
  const decrement$ = sources.DOM
    .select('.decrement').events('click').mapTo(-1);

  const increment$ = sources.DOM
    .select('.increment').events('click').mapTo(+1);

  const action$ = xs.merge(decrement$, increment$);
  const count$ = action$.fold((x, y) => x + y, 0);

  const vdom$ = count$.map(count =>
    div([
      button('.decrement', 'Decrement'),
      button('.increment', 'Increment'),
      p('Counter: ' + count)
    ])
  );
  return { DOM: vdom$ };
}
```
Template for this can be
```html
<div>
  <button @click="decrement$">Decrement</button>
  <button @click="increment$">Increment</button>
  <p>Counter: {count$}</p>
</div>
```
and business logic function is
```typescript
function counter(sources) {
  const decrement$ = sources.decrement$.mapTo(-1);

  const increment$ = sources.increment$.mapTo(+1);

  const action$ = xs.merge(decrement$, increment$);
  const count$ = action$.fold((x, y) => x + y, 0);

  return { count$ };
}
```
Somehow, I feel that `counter` becomes simpler, cause there is no dom there.
Template figures itself that `@click` are places that produce events, hence, these are sources for logic, while other places consume events, and need streams (memory streams?) from logic part. If output stream is missing, template can fail fast with precise error.

**Comment by 3n-mb** [comment]
Note how use of templates shields from use of ids. And classes in such html will be for css styling, not for locating from js.

**Comment by kylecordes** [comment]
This template idea sounds like a much larger thing, to result in a much more different framework to use, than the bit of view boilerplate reduction I have been thinking of - Automatic fine-grained observation.  I'm not sure I fully understand yet how to get optimal results without it.  I wrote a bit of code which suffers from retreating too much VDOM for each change, and I partially (only somewhat effectively) took care of the resulting overhead by using a snabbdom thunk.

I'm not sure whether the template idea would \ preserve what I think is one of the most distringuishing aspects of Cycle: that there is no extra framework-provided layer or magic glue between one component and another. Still, if someone made such a template add on for Cycle it would be quite interesting to try out and compare.

**Comment by 3n-mb** [comment]
@kylecordes I am with you on
> if someone made such a template add on for Cycle it would be quite interesting to try out and compare.

It seems that there can room for experimentation (fun), and it will give more options.

On

> I'm not sure whether the template idea would \ preserve what I think is one of the most distringuishing aspects of Cycle: that there is no extra framework-provided layer or magic glue between one component and another.

Template system should be adding things only between your logic circuit and dom on entry and on exit. All other sources/sinks should be just let to pass through wrapping function, resulting in zero additions between your logical components.
devtool will show you what template system adds, so that you can immediately judge if library tastes good to oneself.
