### ISSUE TITLE
Suggestion: rename MVI to IMV

### ISSUE THREAD

**Issue by aronallen** [cyclejs/cyclejs#622]
Hi,

I think it could make things a lot simpler to call MVI IVM.

- Intent - Model - View is the data-flow order
- Intent - Model - View is the alphabetical order
- Intent - Model - View is how we visualize it in the official documentation.
- C in MVC as i understand it is I and M in Cycle, MVI sounds too similar to MVC, but they are quite different.

**Comment by drewdeal** [comment]
IMV then. :-)

**Comment by staltz** [comment]
Hey @aronallen. The reason why it's called MVI is actually because of similarity with MVC. MVI belongs to the "MV*" family. Here are some others:

- [MVVM](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel)
- [MVP](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93presenter)
- [MVA](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93adapter)
- [HMVI](https://en.wikipedia.org/wiki/Hierarchical_model%E2%80%93view%E2%80%93controller)

Model in MVI is similar to model in MV*, because it describes state and notifies the View of state changes. And the View in MVI is a visual representation of the data from the model. These two definitions of Model and View match really well the original MVC from the 70s: http://heim.ifi.uio.no/~trygver/1979/mvc-2/1979-12-MVC.pdf

So because it starts with "MV", it reflects how it belongs to the MV* family. I don't think people would make that association if the name would be IMV. The renaming could confuse people if the previous name continues to be mentioned, besides beginners could save time and realize how "IMV" is "just like MVC, but with a bit rearrangement and the introduction of Intent".

If you're concerned it may sound like MVC in backend tech, like in Java Spring, well they unfortunately misrepresented MVC in those tech, because Java Spring doesn't handle realtime user interactions like the original MVC was concerned about.
