### ISSUE TITLE
isolateSource(component, scope).events('click') throws errors!

### ISSUE THREAD

**Issue by hatelove85911** [cyclejs/cyclejs#647]
**Code to reproduce the issue:**
```
import {div, button, h2} from '@cycle/dom'
import xs from 'xstream'
import isolate from '@cycle/isolate';

function AButton({DOM, props}) {
  const sinks = {
    DOM: xs.of(
      button('hello')
    )
  }

  return sinks;
}
export function App (sources) {

  const {isolateSource} = sources.DOM;
  const button = isolate(AButton, 'abc')(sources);
  const button2 = isolate(AButton)(sources);

  const vdom$ = xs.combine(button.DOM, button2.DOM)
    .map(([b1, b2]) =>
      div([
        h2('two buttons'),
        b1,
        b2
      ])
    );

  return {
    DOM: vdom$,
    Alert: isolateSource(sources.DOM, 'abc').events('click').map(()=> 'abc')
  }
}
```

**Expected behavior:**
When click on button, it should alert

**Actual behavior:**
it throws error: Uncaught DOMException: Failed to execute 'matches' on 'Element': '' is not a valid selector.

**Versions of packages used:**
    "@cycle/dom": "^17.5.0"
    "@cycle/isolate": "^3.0.0"

**Comment by jvanbruegge** [comment]
As said, `isolateSource` is an internal and undocumented API that should be used with `@cycke/isolate`. I would suggest sibling isolation for your use case. See https://cycle.js.org/api/isolate.html#api

**Comment by staltz** [comment]
@jvanbruegge I was curious why this happened, and it turns it out it behaves unexpectedly (not what I expected at least). Also, I consider `isolateSource` an actual API, not so much internal. Maybe it's "half internal", since we use it through isolate, but anyway, and important API.

But regardless whether it's internal or public API, the fact that it crashes given that example code is weird and could easily be fixed. I'm working on it now, should be an easy fix. This was just a corner case not handled by our code.

**Comment by staltz** [comment]
Thanks @hatelove85911 for reporting it carefully. :)

**Comment by jvanbruegge** [comment]
Interesting, thought it was used the wrong way

**Comment by staltz** [comment]
`dom@17.6` released with this fix.
