### ISSUE TITLE
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#713]
Here is a bug I've met with simple list and items selections:

**Code to reproduce the issue:**

```js
import xs from 'xstream'
import { run } from '@cycle/run'
import { makeDOMDriver, div } from '@cycle/dom'

console.clear()

const Main = ({DOM}) => {
   const selectedIndex$ = DOM.select(`[index]`).events('click')
    .map(ev => parseInt((ev.currentTarget).getAttribute('index')))
    .startWith(0)

   const selectedDOM$ = xs.of(div(['Selected']))
  
  return {
    DOM: xs.combine(selectedIndex$, selectedDOM$)
      .map(([selectedIndex, selectedDOM]) => {
        const list = ['One', 'Two', 'Three']
        return div(
          list.map((item, index) => {
            const isSelected = index === selectedIndex
            return div({
              attrs: {index}
            }, [isSelected ? selectedDOM : item ])
          })
        )
      })
  }
}

run(Main, {
  DOM: makeDOMDriver('body')
})
```

**Expected behavior:**

When clicked the item (`One`, `Two`, or `Three` ) is replaced with `Selected` text.

**Actual behavior:**

After a few clicks:

> DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

![image](https://user-images.githubusercontent.com/736697/31338304-1a82d778-ad18-11e7-8b41-cbfd9fe5ea99.png)

**Versions of packages used:**

![image](https://user-images.githubusercontent.com/736697/31338315-22142226-ad18-11e7-87ba-c72c9a420617.png)

Here is webpackbin:
https://www.webpackbin.com/bins/-Kw01D616yUWznH1mbTA

**Comment by staltz** [comment]
Thanks for the detailed report

**Comment by brucou** [comment]
I had that bug twice too. I fixed it by removing the array. i.e. run your code with replacing `div({              attrs: {index}            }, [isSelected ? selectedDOM : item ])`

by `div({              attrs: {index}            }, isSelected ? selectedDOM : item )`

Now the actual reason of the bug I don't know. I did not investigate further, snabbdom source code is pretty hard to read.

**Comment by whitecolor** [comment]
@brucou right that works

This is supposedly snabbdom problem.

**Comment by staltz** [comment]
It's been hard to debug this issue, but at least one thing I'm sure: we can blame mutability. Something somewhere is mutating the `vnode.elm` field and something is reusing `vnode` throughout two consecutive snabbdom patches.

Experiment with this simple change, and the bug will go away:

```diff
        return div(
          list.map((item, index) => {
            const isSelected = index === selectedIndex
            return div({
              attrs: {index}
-           }, [isSelected ? selectedDOM : item ])
+           }, [isSelected ? div(['Selected']) : item ])
          })
        )
```

That's because `selectedDOM` is not reused, instead we recreate the vnode that has `vnode.elm` undefined.

I'm still looking for the underlying reason. It could be the buffer inside `xs.combine`, but there should be a way of reusing a vnode for different calls to `patch`.

**Comment by brucou** [comment]
It is probably not the buffer of `xs.combine`, I had this bug and I was not using xstream.

**Comment by whitecolor** [comment]
Passng not arrays are not supported by TS typings.

That bug happens when you click on elements that are located BEFORE selected.

**Comment by aronallen** [comment]
I have had similar bugs, I have found mapping the VNode Stream through the following method helps

```typescript
detach(vnode: VNode) {
  return {
    ...vnode,
    elm: undefined,
    children: (vnode.children | []).map(vnode => vnode ? (typeof vnode === 'string' ? vnode : detach(vnode)) : vnode )
  };
}
```

**Comment by aronallen** [comment]
I know @TylorS branched `snabbdom` into `mostly-dom` to handle this issue.
I tried using the patch from `mostly-dom` instead, but there are some breaking changes to the module definitions. Perhaps Tylor can point out where in snabbdom the mutation occours, and how he got around it.

**Comment by jvanbruegge** [comment]
I debugged this issue in snabbdom: https://github.com/snabbdom/snabbdom/issues/395
Currently no solution in sight. The easiest solution is to not reuse vnodes

**Comment by jvanbruegge** [comment]
This is by design, reusing the same vnodes between patches is not supported. I added a section in the README of snabbdom explaining this error

**Comment by fuunnx** [comment]
Hi @jvanbruegge, here are my two cents related to https://github.com/cyclejs/cyclejs/issues/713 :

First, I don't know how much it is desirable to fix this bug for the community. However I encountered the same issue for user generated html that was converted to dynamic vtrees (something inspired by https://github.com/snabbdom/snabbdom-template). I managed to fix it in the scope of my customer's needs :

I forked the snabbdom source code at the points of DOM node creation. Each DOM node creation takes care to shallow-copy the corresponding vnode and mutates the provided vtree BEFORE appending the `.elm` property so that the original vnode/vtree is untouched and reusable anywhere. This operation happens only once on the lifecycle of a DOM element, so it's not really expensive.

I don't have the code at hand right now (and it's hacky at fuck ^^), but I hope you get the idea :

```ts
function createElm(siblings: VNode[], vnode_: VNode, insertedVnodeQueue: VNodeQueue): Node {
    let vnode = vnode_.elm
      ? Object.assign({}, vnode_) 
      : vnode_
    siblings[siblings.indexOf(vnode_)] = vnode
    // ...    
    // later :
    vnode.elm = elm
}
```

Of course I don't understand fully the mechanics of snabbdom and my scope was very narrow. But I did not encounter any issue at this point. 

Any opinion if it could work or would lead to some impredictable behaviour ? There are probably some downsides

Hope it can be usefull :)

**Comment by jvanbruegge** [comment]
The shallow copy is too expensive for snabbdom, I know that it would help, but the case is rare an easy to fix in user code (by said shallow copy) so it's fine as long as it is well documented

**Comment by brucou** [comment]
I was hoping `Object.assign` would be fast? It would be interesting to actually compare how speed is affected by the change to orient the decision. It is not clear that the case is rare, and how rare it actually is, given that we only see those who reported it complaining. I encountered that issue years ago and struggled hours before I decided to just clone vNode. I am happy to know that shallow copy is enough, I was deep copying. But I notified only a few months ago because somebody else did. So it is not easy to conclude about rarity because our observations are necessarily partial.

Anyways I guess the bottom line is whether to make snabbdom's life easier or snabbdom's users life easier... But yes, in any case, documentation and visibility of that documentation is key. If we leave it as is, the 'no duplicated vNode' becomes a contract or precondition to using the library, so it should be proeminently notified.

**Comment by jvanbruegge** [comment]
Alone the fact, that it has to allocate a new object is enough performance impact.

**Comment by fuunnx** [comment]
Sure brucou, here it is :
https://gist.github.com/fuunnx/24dc7745e4d71111e4f83eb2de6255ab

You'll have to use patch-package and work without typescript for now sorry. I'll add the modified .js file instead of the diff file tomorrow when I'm at work.

It's hackish but did work fine for a few months now 😄 . I already tried to optimise it by avoiding to shallow copy the node when it is not necessary :)

**Comment by brucou** [comment]
Thanks, I'll have a deeper look during the week. But from first sight,
there are ways to optimize it performance-wise (specially the
try/catch statements). But I see the idea behind what you are doing.
So it is about estimating the shallow copy costs. I mean I have to
shallow copy always myself in my combinator library because of the bug
anyways so I don't expect it to be a big difference vs. the copying
happening in the library.
My conclusion is that snabbdom is tricky to extend and build upon as
you have to guard against caveats (how would you know when you are
reusing a vNode somewhere deep in the hierarchy), but basic use case
as intended is perfectly fine.


On 9/4/18, Géraud Henrion <notifications@github.com> wrote:
> Sure brucou, here it is :

> https://gist.github.com/fuunnx/24dc7745e4d71111e4f83eb2de6255ab

>

> You'll have to use patch-package and work without typescript for now sorry.
> I'll add the modified .js file instead of the diff file tomorrow when I'm at
> work.

>

> It's hackish but did work fine for a few months now 😄 . I already tried to
> optimise it by avoiding to shallow copy the node when it is not necessary
> :)
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/cyclejs/cyclejs/issues/713#issuecomment-418201110


-- 
---

**Comment by fuunnx** [comment]
Yeah the `try catch`s were there because I was not completely confident in my changes at that time. But it did not throw for a long time so I should remove them now ;)

I've added the modified `snabbdom.js` file
