### ISSUE TITLE
Strange behaviour with preventDefault

### ISSUE THREAD

**Issue by stevenmathews** [cyclejs/cyclejs#738]
**Code to reproduce the issue:**

Here is a minimal reproducer:

https://www.webpackbin.com/bins/-Kyd2PzYUij7MdqEsmpO

```js
function view(isLoggedIn) {
  if (!isLoggedIn) {
    return form([button({ props: { type: "submit" } }, "Log in")]);
  } else {
    return div([button(".logout", "Log out")]);
  }
}

function main(sources) {
  const login$ = sources.DOM.select("form")
    .events("submit", { preventDefault: true })
    .mapTo(true);

  const logout$ = sources.DOM.select(".logout")
    .events("click", { preventDefault: true })
    .mapTo(false);

  const isLoggedIn$ = Stream.merge(login$, logout$).startWith(false);

  return {
    DOM: isLoggedIn$.map(view)
  };
}
```

**Expected behavior:**

When clicking the login button, we should see it disappear and be replaced by the logout button.

**Actual behavior:**

Instead of login button disappearing, it remains. This can be fixed by not using `preventDefault` on the `logout$`, but it seems like a bug that having `preventDefault` on that stream would impact another element entirely.

```diff
   const logout$ = sources.DOM.select(".logout")
-     .events("click", { preventDefault: true })
+     .events("click")
```

**Versions of packages used:**

```
@cycle/dom: 19.3.0
@cycle/run: 3.4.0
```

Attempted to use `20.0.0` and `4.0.0` but then even a simple "Hello world" would not display.

**Comment by staltz** [comment]
Thanks for the detailed report. I'm actually much more worried about cycle/dom 20.0.0 not working for a simple hello world, so I opened #739 which I'm working on fixing ASAP.

**Comment by staltz** [comment]
@stevenmathews Could you please try now using cycle/run `4.0.0` and cycle/dom `20.1.0`? I just issued a new version for cycle/dom.

**Comment by stevenmathews** [comment]
@staltz hello world is working now with the versions you specified.

**Comment by stevenmathews** [comment]
@staltz The preventDefault issue remains if you were asking about that one.

**Comment by staltz** [comment]
Hi @stevenmathews, I debugged your issue. Indeed it's about the `events('click', {preventDefault: true})` and this is mostly due to how the DOM works. Prevent default on that click will cause the event bubbling to be cancelled. With that cancelled, the `form` element will not know that it should emit a `submit` event.

I know it may seem confusing when thinking in streams, but this is a DOM thing. We are looking at different strategies how to create the right abstractions for DOM imperative methods like `preventDefault`, see e.g. issue #727 and #729.
