### ISSUE TITLE
scheduleMicrotask is not a function

### ISSUE THREAD

**Issue by mauroporrasp** [cyclejs/cyclejs#767]
Hi guys
I upgraded to the latest version of `@cycle/run` and I'm getting `schedulemicrotask is not a function`
It doesn't happen with version "^3.0.0"

These are my dependencies:
<img width="675" alt="screen shot 2017-12-27 at 14 44 46" src="https://user-images.githubusercontent.com/167700/34391591-8aee77da-eb14-11e7-9c08-81e6b6adee3a.png">

This is the error:
<img width="517" alt="screen shot 2017-12-27 at 14 45 28" src="https://user-images.githubusercontent.com/167700/34391598-9ca0a7b4-eb14-11e7-9ed9-3371ee932485.png">

**Comment by staltz** [comment]
Hi, could you check your `yarn.lock` file or package-lock file to see whether `redux-cycles` or something else is installing an older version of cycle/run? I think that would be the case since the stacktrace in red shows `createCycleMiddleware`. If that's the case then this should be a redux-cycles issue.

**Comment by mauroporrasp** [comment]
Thanks @staltz, I reported this issue https://github.com/cyclejs/cyclejs/issues/776

Is there any way that I can fix it myself?
