### ISSUE TITLE
@cycle/time does not supports managed Expo

### ISSUE THREAD

**Issue by PEZO19** [cyclejs/cyclejs#960]
After `npm install @cycle/time` Expo (v39) server gives an error: 

> The package at "node_modules/@cycle/time/lib/cjs/src/assert-equal.js" attempted to import the Node standard library module "assert". It failed because the native React runtime does not include the Node standard library. Read more at https://docs.expo.io/workflow/using-libraries/#using-third-party-libraries

**Comment by brucebotes** [comment]
@cycle/time depends on assert.

I have a similar problem when using esbuild instead of browserify as the package manager. Bowserify loads the assert (Node derived package) package/plugin in by default ( if I am not mistaken), whereas the other (esbuild and I assume webpack) do not have similar default plugins. When the assert package is loaded manually with esbuild, it causes downstream issues with references to the  'process.env' variable and the chalk library (the default version  is 5, which is now an ESM module and causes issues when loading assert via unpkg.com/assert - used as an alternative means to plug in assert). Having the Node based assert library as a dependency  is causing lots of issues for other package managers besides browserify. :(

**Comment by PEZO19** [comment]
@brucebotes Thanks!
