### ISSUE TITLE
@cycle/state package problem 1.6.0

### ISSUE THREAD

**Issue by ftaiolivista** [cyclejs/cyclejs#983]
@cycle/state package 1.6.0

declare

` "module": "lib/es6/index.js",`

 in **package.json** (as precendent version)

But **lib/es6/index.js is missing** from the npm files.

**Comment by ryota-ka** [comment]
I also encountered this while I was trying to move from Webpack to Vite.

I downloaded the tarballs of all the available versions of `@cycle/state`, inspected the contents of them, to find out that the problem has been introduced in v1.6.0.

The difference of the contents between v1.5.0 and v1.6.0 is the following:

```diff
$ diff v1.5.0 v1.6.0
25,45d24
< package/lib/es6/Collection.d.ts
< package/lib/es6/Collection.js
< package/lib/es6/Collection.js.map
< package/lib/es6/StateSource.d.ts
< package/lib/es6/StateSource.js
< package/lib/es6/StateSource.js.map
< package/lib/es6/index.d.ts
< package/lib/es6/index.js
< package/lib/es6/index.js.map
< package/lib/es6/pickCombine.d.ts
< package/lib/es6/pickCombine.js
< package/lib/es6/pickCombine.js.map
< package/lib/es6/pickMerge.d.ts
< package/lib/es6/pickMerge.js
< package/lib/es6/pickMerge.js.map
< package/lib/es6/types.d.ts
< package/lib/es6/types.js
< package/lib/es6/types.js.map
< package/lib/es6/withState.d.ts
< package/lib/es6/withState.js
< package/lib/es6/withState.js.map
```

It looks like the whole of `lib/es6/` is missing.

@staltz Have any changes introduced to the build script since v1.5.0?
Are there anything that I can help?

**Comment by jvanbruegge** [comment]
Do idea what happened there, but I pushed `1.6.1` which has all files
