### ISSUE TITLE
Is cycle.js still active?

### ISSUE THREAD

**Issue by macasas** [cyclejs/cyclejs#995]
Is cycle.js in active development? 
Are the create-cycle-app cli and dev tool still current?

Just installed create-cycle-app CLI, its version 5.0.0
Ran it, and it is fails with node-sass error during app creation, node-sass being deprecated and all that.

Dev Tool also fails to run the "dist" script after a parent yarn install. This tool looks excellent, so gutted about that.

**Comment by staltz** [comment]
I actively use Cycle.js as the framework in https://github.com/staltz/manyverse/ and intend to keep using it, I really love the pattern. The framework itself hasn't been updated recently, that is true, mostly due to lack of time and dedication for it. But apart from some parts like the devtool and create-cycle-app (which by the way is not an official tool), Cycle.js is "ready" and doesn't have a lot bugs, so it's a solid dependency to use.

**Comment by macasas** [comment]
This is really great news, and I thank you for taking the time to reassure me that my time has not, and will not be wasted.  So many frameworks get abandoned, and to be honest this does have some of the the signs, except in npmjs.org weekly downloads.  After full days of cycle.js research I was excited about using this "pattern" in my own projects but hesitant due to the issues mentioned. 

I think your talks and explanations are excellent, the basic idea is genius and I'm hoping my implementation flows as well as I've seen in other examples.  I will jump back into learning this as much as I can.

It is a real shame the dev tool no longer builds as it looked like a really useful tool, especially when beginning to use cycle.js and getting used to it.

Thanks again.
